### ISSUE TITLE
How to get final Sensor Data generated?

### ISSUE THREAD

**Issue by asafe199** [yoghurtbot/akamai-bmp-rsa-frida-hook#2]
Hey mate!
I have been working in a project and if you could help me, I appreciate.

I'm using python to hook these methods from your repository, and I noticed the function is called before script Python is running. Is there a way to call `initializeKeyN` multiple times?

Last question, Do you have any clue, what method build the final sensor data after encoded?

**Comment by vikasg603** [comment]
@asafe199 can you comment on how you got the final data?
may be if you can add code snippet
